server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: id-api-customer
          uri: lb://api-customer
          predicates:
            - Path=/api/customer/**
        - id: id-api-wallet
          uri: lb://api-wallet
          predicates:
            - Path=/api/wallet/**
        - id: id-api-margin
          uri: lb://api-margin
          predicates:
            - Path=/api/calculate/**            

info:
  app:
    name: ${spring.application.name}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    gateway:
      enable: true
  endpoints:
    web:
      exposure:
        include: gateway
